### ISSUE TITLE
I got this error and i couldn`t figure out nor find it what is the issue

### ISSUE THREAD

**Issue by Csongor00** [3096/genshin_scripts#19]
loaded 1 songs from config!
loading ghoul.mid
auto root found root at 58 with 404/404 (1.0)
start playing
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<LyrePlayer.play() done, defined at midi.py:169> exception=TypeError("__init__() got an unexpected keyword argument 'type'")>
Traceback (most recent call last):
  File "midi.py", line 194, in play
  File "mido\midifiles\midifiles.py", line 376, in __iter__
  File "mido\midifiles\tracks.py", line 104, in merge_tracks
  File "mido\midifiles\tracks.py", line 62, in _to_abstime
  File "mido\midifiles\meta.py", line 507, in copy
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by Csongor00** [comment]
I might be dumb but can`t i download any mid file?

**Comment by Csongor00** [comment]
ah the mid file could be bad
